### ISSUE TITLE
Add a proper readme file with the models diagram.

### ISSUE THREAD

**Issue by rahulbajaj0509** [lingostack/lingoqa#4]
@tpardeshi please update the README file with a proper content including:
1) Why we are working on this proper
2) What is the project about?
3) Model structure that we are using.

**Comment by pravins** [comment]
I will work on it. Its more clear to me :)
I will do this first week of December, hope that will be fine.

**Comment by pravins** [comment]
Looks, i dont have permission for assigning it to myself.

**Comment by rahulbajaj0509** [comment]
Any updates on this one?

**Comment by rahulbajaj0509** [comment]
@pravins ping! can you update the README page :)

**Comment by pravins** [comment]
Yeah, I will do it next week. Thanks for the ping :)

**Comment by rahulbajaj0509** [comment]
Any progress on this one? Looks like we are getting close to completing this project.

**Comment by pravins** [comment]
I am doing it today.

**Comment by pravins** [comment]
PR submitted : https://github.com/lingostack/lingoqa/pull/24

**Comment by pravins** [comment]
Please assign issue back to me :)

**Comment by rahulbajaj0509** [comment]
Closing this issue as it got fixed in https://github.com/lingostack/lingoqa/pull/24.
